### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by EivindArvesen** [gdubya/skjit#1]
You might want to reconsider the name of your repo, as "skjit" is a Norwegian term that falls somewhere between "skit"/"skitt" and "drit"/"dritt" – roughly "shit"😛

It's also under the Norwegian Wikipedia's [Badwords](https://no.wikipedia.org/wiki/Wikipedia:Badwords#S).

**Comment by gdubya** [comment]
Haha yeah, thanks, it's just a play on words for where I live (Skjetten), in case I ever decide to start my own IT consultancy here ;)

**Comment by gdubya** [comment]
But with the ".no" domain it negates it, right i.e. Shit? no! :D

**Comment by noratessem** [comment]
Path is even better though no.skjit.*
